#!/usr/bin/env bash
# a short and sweet script to configure nginx, port 80
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"